### ISSUE TITLE
Fastify example

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/examples#29]
Can you please add an example using webhook with secret_token, ngrok and fastify? I spent too much time trying to get it to work.

Try to use express v4.18.2, it didn't handle errors..

_Originally posted by @gomez-git in https://github.com/grammyjs/grammY/issues/486#issuecomment-1714747128_

**Comment by KnorpelSenf** [comment]
@gomez-git could you take a look at #30 and leave an approval there if you could make it work?

**Comment by gomez-git** [comment]
> @gomez-git could you take a look at #30 and leave an approval there if you could make it work?

I think about this one

```js
import { Bot, webhookCallback } from 'grammy';
import fastify from 'fastify';
import ngrok from '@ngrok/ngrok';

const { BOT_TOKEN, PORT, SECRET_TOKEN } = process.env;

const bot = new Bot(BOT_TOKEN);

bot.on('message:text', (ctx) => ctx.reply(ctx.message.text));

const server = fastify();

server.post('/webhook', webhookCallback(bot, 'fastify', { secretToken: SECRET_TOKEN })); 

server.listen({ port: +PORT }, async (err, address) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  const url = await ngrok.connect({
    addr: +PORT,
  });
  await bot.api.setWebhook(url, { secret_token: SECRET_TOKEN });
});
```

**Comment by gomez-git** [comment]
> Perhaps we should use the official package https://www.npmjs.com/package/@ngrok/ngrok instead?

I use it in my snippet, isn't it?

**Comment by KnorpelSenf** [comment]
No. You're using https://github.com/bubenshchykov/ngrok. See https://t.me/grammyjs/166618.

**Comment by roj1512** [comment]
@KnorpelSenf They are importing `@ngrok/ngrok` in https://github.com/grammyjs/examples/issues/29#issuecomment-1717688086, 3rd line.

**Comment by KnorpelSenf** [comment]
Oh what

**Comment by KnorpelSenf** [comment]
I'm blind

**Comment by KnorpelSenf** [comment]
Yes, let's do that. @AbbassAlmusawi could you update your code in #30 with the above package? I'll merge after that.

**Comment by gomez-git** [comment]
Dockerfile

```dockerfile
FROM node:18-alpine

WORKDIR /usr/src

COPY ./package*.json ./

EXPOSE 443

RUN npm ci

COPY . ./

CMD ["ts-node", "fastify-ngrok-webhook.ts"]
```

.dockerignore

```
node_modules
```

command

```sh
docker build --tag grammy_fastify_example
docker run --detach \
  --name grammy_fe \
  grammy_fastify_example
```

**Comment by AbbassAlmusawi** [comment]
Done, please see #30 and tell me if there are any mistakes of suggestions
