### ISSUE TITLE
need Nuxt3 example

### ISSUE THREAD

**Issue by IAMSDR** [grammyjs/examples#50]
I want to implement grammyjs in nuxt3.

Any help or guidance would be greatly appreciated.

**Comment by KnorpelSenf** [comment]
Ask a more concrete question and you'll get the answers you need :)

**Comment by IAMSDR** [comment]
i want to handle  webhookCallback in nuxt server 

```
import { bot } from '~/bot'
import { webhookCallback } from 'grammy'

export default webhookCallback(bot,'std/http')
```
i tried like  this in server/api/webhook.ts but it throws **req.json is not a function** error

**Comment by KnorpelSenf** [comment]
There's no adapter for nuxt yet. You can check https://github.com/grammyjs/grammY/blob/main/src/convenience/frameworks.ts and see if a different adapter is compatible, or use the callback adapter with your own logic, or create a completely new adapter for nuxt. If you choose to do the latter, feel free to upstream your changes back to grammY.

**Comment by keyding** [comment]
> i want to handle webhookCallback in nuxt server
> 
> ```
> import { bot } from '~/bot'
> import { webhookCallback } from 'grammy'
> 
> export default webhookCallback(bot,'std/http')
> ```
> 
> i tried like this in server/api/webhook.ts but it throws **req.json is not a function** error

I tried. You can write it like this.

```ts
import { bot } from '~/utils/bot'
import { webhookCallback } from 'grammy'

export default defineEventHandler(async (event) => {
  const handle = webhookCallback(bot, 'http')
  return handle(event.node.req, event.node.res)
})
```

**Comment by keyding** [comment]
PR. https://github.com/grammyjs/examples/pull/54
